### ISSUE TITLE
server启动失败

### ISSUE THREAD

**Issue by gaoqi-code** [qunarcorp/qconfig#5]
https://github.com/qunarcorp/qconfig/blob/master/doc/devStart.md 这个步骤里的图裂了。
server启动时候要加什么参数吗？

server启动后总提示这个 com.sun.jersey.api.client.ClientResponse.getEntity The registered message body readers compatible with the MIME media type are:
   com.sun.jersey.core.impl.provider.entity.FormProvider

admin启动后提示  ： 多次重试仍然无法访问qconfig server 
http://127.0.0.1:8080/client/longPollingCheckupdatev2这个地址访问不到

**Comment by learingL** [comment]
需要EUREKA服务吗 ，我看在访问这个地址呢http://10.232.27.227:8080/
